"""initial schema

The whole schema as of v0.2.0, plus the append-only triggers.

The triggers are here rather than only in application code because
`alembic upgrade head` has to produce a CORRECT database on its own. A schema
with `control_tests` but no trigger on it satisfies nothing: CINV-7 says test
history is immutable, and a table anyone can UPDATE is not immutable however
firmly the service layer declines to. The application re-asserts them
idempotently at boot as well, so APPEND_ONLY_TABLES in db_init.py stays the
authoritative list.

Revision ID: 3453a6b86357
Revises: 
Created: 2026-09-18 20:24:42.756136

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3453a6b86357'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


# Kept in step with APPEND_ONLY_TABLES in app/db_init.py, which re-asserts these
# at boot. A later migration adding an append-only table adds it in both places.
APPEND_ONLY_TABLES = (
    "audit_log",
    "risk_phase_history",
    "policy_versions",
    "control_tests",
    "treatment_checkins",
    "threat_scenario_evidence",
)

IMMUTABILITY_FUNCTION = """
CREATE OR REPLACE FUNCTION grc_reject_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION
        'Table % is append-only: % is not permitted. This enforces the immutability '
        'invariants (CINV-7, PINV-9). Corrections create a new superseding record.',
        TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
"""


def _install_immutability_triggers() -> None:
    op.execute(IMMUTABILITY_FUNCTION)
    for table in APPEND_ONLY_TABLES:
        trigger = "trg_" + table + "_append_only"
        op.execute("DROP TRIGGER IF EXISTS " + trigger + " ON " + table)
        op.execute(
            "CREATE TRIGGER " + trigger
            + " BEFORE UPDATE OR DELETE ON " + table
            + " FOR EACH ROW EXECUTE FUNCTION grc_reject_mutation()"
        )


def _drop_immutability_triggers() -> None:
    for table in APPEND_ONLY_TABLES:
        op.execute("DROP TRIGGER IF EXISTS trg_" + table + "_append_only ON " + table)
    op.execute("DROP FUNCTION IF EXISTS grc_reject_mutation()")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_surfaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_owner_id', sa.String(length=36), nullable=True),
    sa.Column('compliance_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_log',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('compliance_frameworks',
    sa.Column('framework_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('authority', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('redistributable', sa.Boolean(), nullable=False),
    sa.Column('licence_note', sa.Text(), nullable=True),
    sa.Column('adopted', sa.Boolean(), nullable=False),
    sa.Column('adopted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_id', name='uq_compliance_framework_id')
    )
    op.create_table('control_objectives',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('family', sa.String(length=64), nullable=False),
    sa.Column('control_type', sa.String(length=32), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('control_owner_id', sa.String(length=36), nullable=True),
    sa.Column('objective_statement', sa.Text(), nullable=True),
    sa.Column('automation_level', sa.String(length=32), nullable=False),
    sa.Column('implementation_type', sa.String(length=32), nullable=False),
    sa.Column('operating_frequency', sa.String(length=32), nullable=False),
    sa.Column('assurance_method', sa.String(length=32), nullable=False),
    sa.Column('is_key_control', sa.Boolean(), nullable=False),
    sa.Column('failure_declared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remediation_plan', sa.Text(), nullable=True),
    sa.Column('deprecation_rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lifecycle_state IN ('Design', 'Implementation', 'Operating', 'Failure', 'Redesign', 'Deprecated')", name='ck_control_objectives_lifecycle_state'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('notifications',
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('policies',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('policy_type', sa.String(length=48), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('review_cycle', sa.String(length=16), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('compliance_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exception_count', sa.Integer(), nullable=False),
    sa.Column('realignment_pending', sa.Integer(), nullable=False),
    sa.Column('realignment_due', sa.Date(), nullable=True),
    sa.Column('policy_owner_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lifecycle_state IN ('Draft', 'Under_Review', 'Approved', 'Active', 'Under_Revision', 'Deprecated')", name='ck_policies_lifecycle_state'),
    sa.CheckConstraint('approved_by IS NULL OR policy_owner_id IS NULL OR approved_by <> policy_owner_id', name='ck_policies_no_self_approval'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_policies_policy_owner_id'), 'policies', ['policy_owner_id'], unique=False)
    op.create_table('risks',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('threat_event', sa.Text(), nullable=True),
    sa.Column('vulnerability', sa.Text(), nullable=True),
    sa.Column('impact_statement', sa.Text(), nullable=True),
    sa.Column('intake_source', sa.String(length=48), nullable=True),
    sa.Column('identified_by', sa.String(length=200), nullable=True),
    sa.Column('pre_true_risk_confirmed', sa.Boolean(), nullable=False),
    sa.Column('pre_tier_assigned', sa.Boolean(), nullable=False),
    sa.Column('pre_stakeholders_identified', sa.Boolean(), nullable=False),
    sa.Column('pre_ce_assessed', sa.Boolean(), nullable=False),
    sa.Column('precondition_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=True),
    sa.Column('tier_rationale', sa.Text(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.Column('likelihood', sa.Integer(), nullable=True),
    sa.Column('inherent_risk_score', sa.Integer(), nullable=True),
    sa.Column('inherent_rating', sa.String(length=16), nullable=True),
    sa.Column('impact_justification', sa.Text(), nullable=True),
    sa.Column('likelihood_justification', sa.Text(), nullable=True),
    sa.Column('inherent_locked', sa.Boolean(), nullable=False),
    sa.Column('treatment_strategy', sa.String(length=16), nullable=True),
    sa.Column('acceptance_expiry_date', sa.Date(), nullable=True),
    sa.Column('acceptance_rationale', sa.Text(), nullable=True),
    sa.Column('acceptance_approved_by', sa.String(length=36), nullable=True),
    sa.Column('acceptance_reassessment_count', sa.Integer(), nullable=False),
    sa.Column('transfer_description', sa.Text(), nullable=True),
    sa.Column('avoidance_description', sa.Text(), nullable=True),
    sa.Column('partial_treatment_rationale', sa.Text(), nullable=True),
    sa.Column('control_framework_mapping', sa.Text(), nullable=True),
    sa.Column('readout_confirmed', sa.Boolean(), nullable=False),
    sa.Column('readout_conducted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('readout_adjustment_rationale', sa.Text(), nullable=True),
    sa.Column('gate_mitigations_implemented', sa.Boolean(), nullable=False),
    sa.Column('gate_evidence_provided', sa.Boolean(), nullable=False),
    sa.Column('gate_effectiveness_confirmed', sa.Boolean(), nullable=False),
    sa.Column('gate_governance_approved', sa.Boolean(), nullable=False),
    sa.Column('gate_drift_tracked', sa.Boolean(), nullable=False),
    sa.Column('evidence_ref', sa.Text(), nullable=True),
    sa.Column('residual_gate_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('residual_score_locked', sa.Boolean(), nullable=False),
    sa.Column('residual_impact', sa.Integer(), nullable=True),
    sa.Column('residual_likelihood', sa.Integer(), nullable=True),
    sa.Column('residual_risk_score', sa.Integer(), nullable=True),
    sa.Column('residual_rating', sa.String(length=16), nullable=True),
    sa.Column('residual_impact_rationale', sa.Text(), nullable=True),
    sa.Column('residual_likelihood_rationale', sa.Text(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('sla_status', sa.String(length=16), nullable=False),
    sa.Column('escalation_flag', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('control_change_flag', sa.String(length=64), nullable=True),
    sa.Column('control_change_detail', sa.Text(), nullable=True),
    sa.Column('reassessment_count', sa.Integer(), nullable=False),
    sa.Column('closure_rationale', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=36), nullable=True),
    sa.Column('risk_owner_id', sa.String(length=36), nullable=True),
    sa.Column('risk_stakeholder_id', sa.String(length=36), nullable=True),
    sa.Column('risk_analyst_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("inherent_rating IS NULL OR inherent_rating IN ('Low', 'Moderate-Low', 'Moderate', 'High', 'Critical')", name='ck_risks_inherent_rating'),
    sa.CheckConstraint("lifecycle_state IN ('Intake', 'Preconditions', 'Scoring', 'Treatment', 'Readout', 'Evidence_Residual', 'Monitoring', 'Closed')", name='ck_risks_lifecycle_state'),
    sa.CheckConstraint("residual_rating IS NULL OR residual_rating IN ('Low', 'Moderate-Low', 'Moderate', 'High', 'Critical')", name='ck_risks_residual_rating'),
    sa.CheckConstraint("sla_status IN ('On_Track', 'At_Risk', 'Breached')", name='ck_risks_sla_status'),
    sa.CheckConstraint("treatment_strategy IS DISTINCT FROM 'Accept' OR acceptance_expiry_date IS NOT NULL", name='ck_risks_acceptance_time_bound'),
    sa.CheckConstraint("treatment_strategy IS DISTINCT FROM 'Accept' OR inherent_rating IS DISTINCT FROM 'Critical'", name='ck_risks_critical_never_accepted'),
    sa.CheckConstraint("treatment_strategy IS NULL OR treatment_strategy IN ('Accept', 'Mitigate', 'Transfer', 'Avoid')", name='ck_risks_treatment_strategy'),
    sa.CheckConstraint('impact IS NULL OR impact BETWEEN 1 AND 5', name='ck_risks_impact'),
    sa.CheckConstraint('likelihood IS NULL OR likelihood BETWEEN 1 AND 5', name='ck_risks_likelihood'),
    sa.CheckConstraint('phase BETWEEN 1 AND 7', name='ck_risks_phase'),
    sa.CheckConstraint('residual_impact IS NULL OR residual_impact BETWEEN 1 AND 5', name='ck_risks_residual_impact'),
    sa.CheckConstraint('residual_likelihood IS NULL OR residual_likelihood BETWEEN 1 AND 5', name='ck_risks_residual_likelihood'),
    sa.CheckConstraint('risk_owner_id IS NULL OR risk_stakeholder_id IS NULL OR risk_owner_id <> risk_stakeholder_id', name='ck_risks_sep1_owner_not_stakeholder'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_risks_risk_owner_id'), 'risks', ['risk_owner_id'], unique=False)
    op.create_table('treatments',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('treatment_type', sa.String(length=16), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('grc_eng_validated', sa.Boolean(), nullable=False),
    sa.Column('grc_eng_validated_by', sa.String(length=36), nullable=True),
    sa.Column('grc_eng_validation_notes', sa.Text(), nullable=True),
    sa.Column('owner_committed', sa.Boolean(), nullable=False),
    sa.Column('owner_committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('treatment_owner_id', sa.String(length=36), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loe', sa.String(length=8), nullable=True),
    sa.Column('loe_implementation_hours', sa.Integer(), nullable=True),
    sa.Column('loe_operational_hours_pa', sa.Integer(), nullable=True),
    sa.Column('cost_implementation', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost_operational_pa', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_impact_delta', sa.Integer(), nullable=False),
    sa.Column('expected_likelihood_delta', sa.Integer(), nullable=False),
    sa.Column('check_in_frequency', sa.String(length=16), nullable=True),
    sa.Column('last_checkin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_checkin_due', sa.Date(), nullable=True),
    sa.Column('evidence_ref', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lifecycle_state IN ('Proposed', 'Validated', 'Approved', 'In_Progress', 'Complete', 'Cancelled')", name='ck_treatments_lifecycle_state'),
    sa.CheckConstraint("treatment_type IN ('Accept', 'Mitigate', 'Transfer', 'Avoid')", name='ck_treatments_type'),
    sa.CheckConstraint('expected_impact_delta BETWEEN -4 AND 0', name='ck_treatments_impact_delta'),
    sa.CheckConstraint('expected_likelihood_delta BETWEEN -4 AND 0', name='ck_treatments_likelihood_delta'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_treatments_treatment_owner_id'), 'treatments', ['treatment_owner_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('seniority', sa.String(length=32), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('compliance_requirements',
    sa.Column('framework_id', sa.String(length=36), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_id', 'ref', name='uq_requirement_ref_per_framework')
    )
    op.create_index(op.f('ix_compliance_requirements_framework_id'), 'compliance_requirements', ['framework_id'], unique=False)
    op.create_table('control_activities',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('objective_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('control_operator_id', sa.String(length=36), nullable=True),
    sa.Column('suspension_rationale', sa.Text(), nullable=True),
    sa.Column('automation_level', sa.String(length=32), nullable=True),
    sa.Column('operating_frequency', sa.String(length=32), nullable=True),
    sa.Column('procedure_ref', sa.Text(), nullable=True),
    sa.Column('tooling', sa.String(length=200), nullable=True),
    sa.Column('evidence_type', sa.String(length=48), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lifecycle_state IN ('Draft', 'Active', 'Suspended', 'Retired')", name='ck_control_activities_lifecycle_state'),
    sa.ForeignKeyConstraint(['objective_id'], ['control_objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('policy_controls',
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('objective_id', sa.String(length=36), nullable=False),
    sa.Column('realignment_required', sa.Boolean(), nullable=False),
    sa.Column('realignment_due', sa.Date(), nullable=True),
    sa.Column('linked_by', sa.String(length=36), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['control_objectives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'objective_id', name='uq_policy_controls')
    )
    op.create_index(op.f('ix_policy_controls_policy_id'), 'policy_controls', ['policy_id'], unique=False)
    op.create_table('policy_exceptions',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('business_justification', sa.Text(), nullable=False),
    sa.Column('risk_statement', sa.Text(), nullable=True),
    sa.Column('compensating_controls', sa.Text(), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('rejection_rationale', sa.Text(), nullable=True),
    sa.Column('promoted_risk_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lifecycle_state IN ('Requested', 'Approved', 'Rejected', 'Expired')", name='ck_policy_exceptions_lifecycle_state'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_policy_exceptions_policy_id'), 'policy_exceptions', ['policy_id'], unique=False)
    op.create_table('policy_versions',
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('lifecycle_state_at_capture', sa.String(length=32), nullable=True),
    sa.Column('edited_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.create_table('risk_comments',
    sa.Column('risk_id', sa.String(length=36), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['risk_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_comments_risk_id'), 'risk_comments', ['risk_id'], unique=False)
    op.create_table('risk_controls',
    sa.Column('risk_id', sa.String(length=36), nullable=False),
    sa.Column('objective_id', sa.String(length=36), nullable=False),
    sa.Column('ce_at_assessment', sa.String(length=32), nullable=True),
    sa.Column('linked_by', sa.String(length=36), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['control_objectives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_id', 'objective_id', name='uq_risk_controls')
    )
    op.create_index(op.f('ix_risk_controls_risk_id'), 'risk_controls', ['risk_id'], unique=False)
    op.create_table('risk_phase_history',
    sa.Column('risk_id', sa.String(length=36), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=True),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('from_phase', sa.Integer(), nullable=True),
    sa.Column('to_phase', sa.Integer(), nullable=False),
    sa.Column('gate', sa.String(length=64), nullable=True),
    sa.Column('gate_evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_phase_history_risk_id'), 'risk_phase_history', ['risk_id'], unique=False)
    op.create_table('risk_policy_links',
    sa.Column('risk_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('linked_by', sa.String(length=36), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_id', 'policy_id', name='uq_risk_policy_links')
    )
    op.create_index(op.f('ix_risk_policy_links_risk_id'), 'risk_policy_links', ['risk_id'], unique=False)
    op.create_table('risk_treatments',
    sa.Column('risk_id', sa.String(length=36), nullable=False),
    sa.Column('treatment_id', sa.String(length=36), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('linked_by', sa.String(length=36), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_id', 'treatment_id', name='uq_risk_treatments')
    )
    op.create_index(op.f('ix_risk_treatments_risk_id'), 'risk_treatments', ['risk_id'], unique=False)
    op.create_table('standards',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('parent_policy_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('review_cycle', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('compliance_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lifecycle_state IN ('Draft', 'Under_Review', 'Approved', 'Active', 'Under_Revision', 'Deprecated')", name='ck_standards_lifecycle_state'),
    sa.ForeignKeyConstraint(['parent_policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('threat_models',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('attack_surface_id', sa.String(length=36), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('methodology', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_owner_id', sa.String(length=36), nullable=False),
    sa.Column('appsec_partner_id', sa.String(length=36), nullable=True),
    sa.Column('appsec_signoff_by', sa.String(length=36), nullable=True),
    sa.Column('appsec_signoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_signoff_by', sa.String(length=36), nullable=True),
    sa.Column('owner_signoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signoff_stripped_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lifecycle_state IN ('Scope', 'Decomposition', 'Threat_Analysis', 'Mitigation_Design', 'Review', 'Active', 'Deprecated', 'Abandoned')", name='ck_threat_models_lifecycle_state'),
    sa.CheckConstraint('appsec_signoff_by IS NULL OR appsec_signoff_by <> system_owner_id', name='ck_threat_models_appsec_independent'),
    sa.ForeignKeyConstraint(['attack_surface_id'], ['attack_surfaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('treatment_approvals',
    sa.Column('treatment_id', sa.String(length=36), nullable=False),
    sa.Column('approval_type', sa.String(length=48), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('proposed_new_date', sa.Date(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decision_by', sa.String(length=36), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("decision IN ('Pending', 'Approved', 'Rejected')", name='ck_treatment_approvals_decision'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_approvals_treatment_id'), 'treatment_approvals', ['treatment_id'], unique=False)
    op.create_table('treatment_checkins',
    sa.Column('treatment_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_checkins_treatment_id'), 'treatment_checkins', ['treatment_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=48), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_roles_user_role')
    )
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('control_deployments',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('attack_surface_id', sa.String(length=36), nullable=False),
    sa.Column('deployment_status', sa.String(length=32), nullable=False),
    sa.Column('ce_rating', sa.String(length=32), nullable=False),
    sa.Column('ce_evidence_ref', sa.Text(), nullable=True),
    sa.Column('ce_assessed_by', sa.String(length=36), nullable=True),
    sa.Column('ce_assessed_at', sa.Date(), nullable=True),
    sa.Column('ce_notes', sa.Text(), nullable=True),
    sa.Column('test_frequency', sa.String(length=32), nullable=False),
    sa.Column('last_test_result', sa.String(length=32), nullable=False),
    sa.Column('last_tested_date', sa.Date(), nullable=True),
    sa.Column('next_test_due', sa.Date(), nullable=True),
    sa.Column('decommission_rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ce_rating = 'CE-Unvalidated' OR ce_evidence_ref IS NOT NULL", name='ck_control_deployments_ce_evidence_required'),
    sa.CheckConstraint("ce_rating IN ('CE-Unvalidated', 'CE-Low', 'CE-Medium', 'CE-High')", name='ck_control_deployments_ce_rating'),
    sa.CheckConstraint("deployment_status IN ('Planned', 'Active', 'Degraded', 'Failed', 'Decommissioned')", name='ck_control_deployments_status'),
    sa.CheckConstraint("last_test_result IN ('Not_Tested', 'Pass', 'Partial', 'Fail')", name='ck_control_deployments_test_result'),
    sa.ForeignKeyConstraint(['activity_id'], ['control_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attack_surface_id'], ['attack_surfaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'attack_surface_id', name='uq_deployment_activity_asset'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('control_requirement_links',
    sa.Column('objective_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('coverage_level', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('asserted_by', sa.String(length=36), nullable=True),
    sa.Column('asserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['control_objectives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['compliance_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('objective_id', 'requirement_id', name='uq_control_requirement')
    )
    op.create_index(op.f('ix_control_requirement_links_objective_id'), 'control_requirement_links', ['objective_id'], unique=False)
    op.create_index(op.f('ix_control_requirement_links_requirement_id'), 'control_requirement_links', ['requirement_id'], unique=False)
    op.create_table('requirement_assessments',
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('assessed_by', sa.String(length=36), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compensating_expiry', sa.Date(), nullable=True),
    sa.Column('gap_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lifecycle_state <> 'Compensating' OR compensating_expiry IS NOT NULL", name='ck_requirement_assessments_compensating_time_bound'),
    sa.CheckConstraint("lifecycle_state <> 'Not_Applicable' OR rationale IS NOT NULL", name='ck_requirement_assessments_exclusion_justified'),
    sa.CheckConstraint("lifecycle_state IN ('Not_Assessed', 'Not_Applicable', 'Applicable', 'Covered', 'Compensating', 'Gap')", name='ck_requirement_assessments_state'),
    sa.ForeignKeyConstraint(['requirement_id'], ['compliance_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', name='uq_assessment_per_requirement')
    )
    op.create_index(op.f('ix_requirement_assessments_requirement_id'), 'requirement_assessments', ['requirement_id'], unique=False)
    op.create_table('threat_components',
    sa.Column('threat_model_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('component_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_classification', sa.String(length=48), nullable=True),
    sa.Column('data_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trust_zone', sa.String(length=48), nullable=True),
    sa.Column('exposure', sa.String(length=48), nullable=True),
    sa.Column('attack_surface_id', sa.String(length=36), nullable=True),
    sa.Column('source_component_id', sa.String(length=36), nullable=True),
    sa.Column('target_component_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("component_type IN ('Process', 'Datastore', 'External_Entity', 'Data_Flow', 'Trust_Boundary')", name='ck_threat_components_type'),
    sa.ForeignKeyConstraint(['attack_surface_id'], ['attack_surfaces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['threat_model_id'], ['threat_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_components_threat_model_id'), 'threat_components', ['threat_model_id'], unique=False)
    op.create_table('control_tests',
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('evidence_ref', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tested_by', sa.String(length=36), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("result IN ('Not_Tested', 'Pass', 'Partial', 'Fail')", name='ck_control_tests_result'),
    sa.ForeignKeyConstraint(['deployment_id'], ['control_deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_scenarios',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('threat_model_id', sa.String(length=36), nullable=False),
    sa.Column('component_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('inherent_severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('remediation_target_date', sa.Date(), nullable=True),
    sa.Column('acceptance_expiry', sa.Date(), nullable=True),
    sa.Column('acceptance_rationale', sa.Text(), nullable=True),
    sa.Column('promoted_risk_id', sa.String(length=36), nullable=True),
    sa.Column('reopened_reason', sa.Text(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status_rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('Spoofing', 'Tampering', 'Repudiation', 'Information_Disclosure', 'Denial_of_Service', 'Elevation_of_Privilege')", name='ck_threat_scenarios_category'),
    sa.CheckConstraint("inherent_severity IN ('Low', 'Medium', 'High', 'Critical')", name='ck_threat_scenarios_severity'),
    sa.CheckConstraint("status <> 'Accepted' OR acceptance_expiry IS NOT NULL", name='ck_threat_scenarios_acceptance_time_bound'),
    sa.CheckConstraint("status <> 'Accepted' OR inherent_severity = 'Low'", name='ck_threat_scenarios_no_local_acceptance_above_low'),
    sa.CheckConstraint("status <> 'Promoted_To_Risk' OR promoted_risk_id IS NOT NULL", name='ck_threat_scenarios_promotion_linked'),
    sa.CheckConstraint("status IN ('Identified', 'Mitigated', 'Accepted', 'Promoted_To_Risk')", name='ck_threat_scenarios_status'),
    sa.ForeignKeyConstraint(['component_id'], ['threat_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promoted_risk_id'], ['risks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['threat_model_id'], ['threat_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_threat_scenarios_threat_model_id'), 'threat_scenarios', ['threat_model_id'], unique=False)
    op.create_table('threat_mitigation_links',
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('effectiveness_assurance', sa.String(length=32), nullable=False),
    sa.Column('linked_by', sa.String(length=36), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("effectiveness_assurance IN ('Fully_Mitigated', 'Partially_Mitigated')", name='ck_threat_mitigation_assurance'),
    sa.ForeignKeyConstraint(['deployment_id'], ['control_deployments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['threat_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'deployment_id', name='uq_threat_mitigation')
    )
    op.create_index(op.f('ix_threat_mitigation_links_deployment_id'), 'threat_mitigation_links', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_threat_mitigation_links_scenario_id'), 'threat_mitigation_links', ['scenario_id'], unique=False)
    op.create_table('threat_scenario_comments',
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['threat_scenario_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['threat_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_scenario_comments_scenario_id'), 'threat_scenario_comments', ['scenario_id'], unique=False)
    op.create_table('threat_scenario_evidence',
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('evidence_ref', sa.Text(), nullable=False),
    sa.Column('evidence_type', sa.String(length=48), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('supports', sa.String(length=48), nullable=True),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['threat_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_scenario_evidence_scenario_id'), 'threat_scenario_evidence', ['scenario_id'], unique=False)
    op.create_table('threat_scenario_risk_links',
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('risk_id', sa.String(length=36), nullable=False),
    sa.Column('link_type', sa.String(length=48), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('linked_by', sa.String(length=36), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['threat_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'risk_id', name='uq_threat_scenario_risk')
    )
    op.create_index(op.f('ix_threat_scenario_risk_links_risk_id'), 'threat_scenario_risk_links', ['risk_id'], unique=False)
    op.create_index(op.f('ix_threat_scenario_risk_links_scenario_id'), 'threat_scenario_risk_links', ['scenario_id'], unique=False)
    # ### end Alembic commands ###

    # After the tables exist, not before: a trigger needs its table.
    _install_immutability_triggers()


def downgrade() -> None:
    # This drops every governance record, including the audit trail that exists
    # to survive exactly this kind of operation. It is here because a migration
    # without a downgrade cannot be tested, not because running it against real
    # data is ever the right answer.
    _drop_immutability_triggers()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_scenario_risk_links_scenario_id'), table_name='threat_scenario_risk_links')
    op.drop_index(op.f('ix_threat_scenario_risk_links_risk_id'), table_name='threat_scenario_risk_links')
    op.drop_table('threat_scenario_risk_links')
    op.drop_index(op.f('ix_threat_scenario_evidence_scenario_id'), table_name='threat_scenario_evidence')
    op.drop_table('threat_scenario_evidence')
    op.drop_index(op.f('ix_threat_scenario_comments_scenario_id'), table_name='threat_scenario_comments')
    op.drop_table('threat_scenario_comments')
    op.drop_index(op.f('ix_threat_mitigation_links_scenario_id'), table_name='threat_mitigation_links')
    op.drop_index(op.f('ix_threat_mitigation_links_deployment_id'), table_name='threat_mitigation_links')
    op.drop_table('threat_mitigation_links')
    op.drop_index(op.f('ix_threat_scenarios_threat_model_id'), table_name='threat_scenarios')
    op.drop_table('threat_scenarios')
    op.drop_table('control_tests')
    op.drop_index(op.f('ix_threat_components_threat_model_id'), table_name='threat_components')
    op.drop_table('threat_components')
    op.drop_index(op.f('ix_requirement_assessments_requirement_id'), table_name='requirement_assessments')
    op.drop_table('requirement_assessments')
    op.drop_index(op.f('ix_control_requirement_links_requirement_id'), table_name='control_requirement_links')
    op.drop_index(op.f('ix_control_requirement_links_objective_id'), table_name='control_requirement_links')
    op.drop_table('control_requirement_links')
    op.drop_table('control_deployments')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_treatment_checkins_treatment_id'), table_name='treatment_checkins')
    op.drop_table('treatment_checkins')
    op.drop_index(op.f('ix_treatment_approvals_treatment_id'), table_name='treatment_approvals')
    op.drop_table('treatment_approvals')
    op.drop_table('threat_models')
    op.drop_table('standards')
    op.drop_index(op.f('ix_risk_treatments_risk_id'), table_name='risk_treatments')
    op.drop_table('risk_treatments')
    op.drop_index(op.f('ix_risk_policy_links_risk_id'), table_name='risk_policy_links')
    op.drop_table('risk_policy_links')
    op.drop_index(op.f('ix_risk_phase_history_risk_id'), table_name='risk_phase_history')
    op.drop_table('risk_phase_history')
    op.drop_index(op.f('ix_risk_controls_risk_id'), table_name='risk_controls')
    op.drop_table('risk_controls')
    op.drop_index(op.f('ix_risk_comments_risk_id'), table_name='risk_comments')
    op.drop_table('risk_comments')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_policy_exceptions_policy_id'), table_name='policy_exceptions')
    op.drop_table('policy_exceptions')
    op.drop_index(op.f('ix_policy_controls_policy_id'), table_name='policy_controls')
    op.drop_table('policy_controls')
    op.drop_table('control_activities')
    op.drop_index(op.f('ix_compliance_requirements_framework_id'), table_name='compliance_requirements')
    op.drop_table('compliance_requirements')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_treatments_treatment_owner_id'), table_name='treatments')
    op.drop_table('treatments')
    op.drop_index(op.f('ix_risks_risk_owner_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_policies_policy_owner_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('control_objectives')
    op.drop_table('compliance_frameworks')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('attack_surfaces')
    # ### end Alembic commands ###
