"""derive phase 2 preconditions

Drops the three stored Phase 2 attestations. RINV-8 said all four preconditions
must hold before scoring opens; three of them were booleans a user ticked, so
what the rule required was that somebody had ticked four boxes. A risk with no
owner, no tier rationale and no linked control could satisfy all three.

They are now read from the record: tier plus rationale, the three named roles,
and a linked control the scoring engine would actually count. Only "this is a
risk, not an issue" remains a tick, because that is a judgement.

There is no data migration. The columns held assertions, not facts, and the
facts they asserted are either present in the record or were never true.

Revision ID: aaa34e5fc638
Revises: 3453a6b86357
Created: 2026-09-20 09:47:48.856721

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'aaa34e5fc638'
down_revision: str | None = '3453a6b86357'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risks', 'pre_stakeholders_identified')
    op.drop_column('risks', 'pre_ce_assessed')
    op.drop_column('risks', 'pre_tier_assigned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Autogenerate wrote these as NOT NULL with no default, which fails on any
    # table that already has rows. They are added with a default so existing
    # risks get a value, and the default is then dropped so the column matches
    # what the old model declared.
    for column in ("pre_tier_assigned", "pre_ce_assessed", "pre_stakeholders_identified"):
        op.add_column(
            "risks",
            sa.Column(column, sa.Boolean(), nullable=False, server_default=sa.false()),
        )
        op.alter_column("risks", column, server_default=None)
