import { useEffect, useState } from 'react'
import { api } from '../lib/api'
import { PageHeader } from '../components/Layout'
import { Badge, Card, PageLoader, Table, Tabs } from '../components/ui'
import { Heatmap, InvariantList, MachineTable } from '../components/governance'
import { cx, label } from '../lib/format'

export default function Engine() {
  const [machines, setMachines] = useState<any>(null)
  const [invariants, setInvariants] = useState<any>(null)
  const [cascades, setCascades] = useState<any>(null)
  const [scoring, setScoring] = useState<any>(null)
  const [tab, setTab] = useState('machines')

  useEffect(() => {
    api.get('/engine/machines').then(setMachines).catch(() => undefined)
    api.get('/engine/invariants').then(setInvariants).catch(() => undefined)
    api.get('/engine/cascades').then(setCascades).catch(() => undefined)
    api.get('/engine/scoring').then(setScoring).catch(() => undefined)
  }, [])

  if (!machines || !invariants || !cascades || !scoring) return <PageLoader />

  const machineCount = Object.keys(machines).length
  const transitionCount = Object.values(machines).reduce(
    (sum: number, m: any) => sum + m.transitions.length,
    0,
  )

  return (
    <>
      <PageHeader
        title="Engine"
        description="Everything on this page is read live from the running engine, not transcribed from a document. If a rule is listed here, it is enforced; if it is enforced, it is listed here."
        meta={
          <>
            <span className="chip border-line bg-surface-sunken text-ink-muted">
              {machineCount} state machines
            </span>
            <span className="chip border-line bg-surface-sunken text-ink-muted">
              {transitionCount} gated transitions
            </span>
            <span className="chip border-line bg-surface-sunken text-ink-muted">
              {invariants.total} invariants
            </span>
            <span className="chip border-line bg-surface-sunken text-ink-muted">
              {cascades.events.length} cascade events
            </span>
          </>
        }
      />

      <div className="mb-5">
        <Tabs
          tabs={[
            { id: 'machines', label: 'State machines', count: machineCount },
            { id: 'invariants', label: 'Invariant catalogue', count: invariants.total },
            { id: 'cascades', label: 'Cascades', count: cascades.events.length },
            { id: 'scoring', label: 'Scoring model' },
          ]}
          active={tab}
          onChange={setTab}
        />
      </div>

      {tab === 'machines' && (
        <div className="space-y-4">
          {Object.values(machines).map((m: any) => (
            <MachineTable key={m.entity} machine={m} />
          ))}
        </div>
      )}

      {tab === 'invariants' && (
        <div className="space-y-4">
          {Object.entries(invariants.by_entity).map(([entity, items]: [string, any]) => (
            <Card
              key={entity}
              title={label(entity)}
              subtitle={`${items.length} invariants, evaluated on every write to this entity`}
            >
              <InvariantList invariants={items} />
            </Card>
          ))}
        </div>
      )}

      {tab === 'cascades' && (
        <Card
          title="Registered cascade events"
          subtitle="A cascade runs inside the transaction that triggered it, so the state change, its downstream effects and the audit entries commit together or not at all."
          bodyClassName="p-0"
        >
          <Table columns={['Event', 'Handlers', 'Behaviour']}>
            {cascades.events.map((e: any) => (
              <tr key={e.event} className="hover:bg-surface-sunken/60">
                <td className="table-cell mono whitespace-nowrap text-ink">{e.event}</td>
                <td className="table-cell text-sm tabular-nums text-ink-muted">{e.handlers}</td>
                <td className="table-cell text-sm text-ink-muted">{e.description || '—'}</td>
              </tr>
            ))}
          </Table>
        </Card>
      )}

      {tab === 'scoring' && (
        <div className="grid gap-4 lg:grid-cols-2">
          <Card
            title="5 × 5 matrix"
            subtitle="Generated by the engine, not transcribed. Score is impact × likelihood (CALC-1)."
          >
            <Heatmap counts={{}} />
            <div className="mt-4 flex flex-wrap gap-2">
              {scoring.bands.map((b: any) => (
                <span key={b.rating} className="chip border-line bg-surface-sunken">
                  <Badge value={b.rating} />
                  <span className="ml-1 tabular-nums text-ink-muted">
                    {b.min}–{b.max}
                  </span>
                </span>
              ))}
            </div>
          </Card>

          <Card
            title="Control effectiveness to likelihood"
            subtitle="LKH-1: the ceiling on how far residual likelihood may fall below inherent."
          >
            <Table columns={['Rating', 'Max likelihood reduction', 'Evidence expiry by cadence']}>
              {Object.entries(scoring.ce_likelihood_reduction).map(([ce, reduction]: any) => (
                <tr key={ce}>
                  <td className="table-cell">
                    <Badge value={ce} />
                  </td>
                  <td className="table-cell text-sm tabular-nums text-ink">
                    {reduction === 0 ? 'none' : `${reduction} level${reduction === 1 ? '' : 's'}`}
                  </td>
                  <td className="table-cell text-xs text-ink-muted">
                    {Object.entries(scoring.ce_expiry_months)
                      .map(([freq, months]: any) => `${freq}: ${months}m`)
                      .join(' · ')}
                  </td>
                </tr>
              ))}
            </Table>
          </Card>

          <Card
            className="lg:col-span-2"
            title="Acceptance and review rules by rating"
            subtitle="RINV-5 makes Critical unacceptable. Everything else is time-bound and capped."
            bodyClassName="p-0"
          >
            <Table
              columns={[
                'Rating',
                'Appetite',
                'Acceptable',
                'Max acceptance window',
                'Minimum approver',
                'Review cadence',
              ]}
            >
              {['Critical', 'High', 'Moderate', 'Moderate-Low', 'Low'].map((rating) => {
                const rule = scoring.acceptance_rules[rating]
                return (
                  <tr key={rating}>
                    <td className="table-cell">
                      <Badge value={rating} />
                    </td>
                    <td className="table-cell text-sm text-ink-muted">
                      {rating === 'Low'
                        ? 'Within appetite'
                        : rating === 'Moderate-Low'
                          ? 'At appetite'
                          : 'Above appetite'}
                    </td>
                    <td className="table-cell">
                      <span
                        className={cx(
                          'chip',
                          rule.acceptable
                            ? 'border-line bg-surface-sunken text-ink-muted'
                            : 'border-rose-300 bg-rose-50 text-rose-700 dark:border-rose-900 dark:bg-rose-950/60 dark:text-rose-300',
                        )}
                      >
                        {rule.acceptable ? 'yes' : 'never (RINV-5)'}
                      </span>
                    </td>
                    <td className="table-cell text-sm tabular-nums text-ink-muted">
                      {rule.acceptable ? `${rule.max_days} days` : '—'}
                    </td>
                    <td className="table-cell text-sm text-ink-muted">
                      {rule.approver ?? '—'}
                    </td>
                    <td className="table-cell text-sm tabular-nums text-ink-muted">
                      {scoring.review_cadence_days[rating]} days
                    </td>
                  </tr>
                )
              })}
            </Table>
          </Card>
        </div>
      )}
    </>
  )
}
